# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
#  adapter: jdbcmysql
#  encoding: utf8
#  database: furnitureapp_development
#  pool: 5
#  username: root
#  password: root

default: &default
 adapter: mysql2
 username: root
 password: root
 pool: 8
 
development:
  <<: *default
  database: raddit_development


