# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49fdff27d5389cf25acbc1d04f27f7af5c3c8d4e7b8d0b0407b1f8e3c476660474d2f2a6ea9bd5cb26c398c625454a04427363e390391c0c4c73f1582a4eaf86

test:
  secret_key_base: b85d0b139ac00c1b827b580a8ad312f0767338c4c1b358954da702c6302ee6707e61a0d06cc9bce17d581191308cc8052c876dd1a0705158000364533e6e064b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
